### ISSUE TITLE
what is gamma used for?

### ISSUE THREAD

**Issue by xhsoldier** [wangwei2009/DOA#1]
float gamma[Nele] = { 0,90,180,270 };//麦克风位置
why there is no distance between mics?

**Comment by wangwei2009** [comment]
在CalculateTau函数里有定义

**Comment by wangwei2009** [comment]
@xhsoldier 在CalculateTau函数里有定义

**Comment by 979527040** [comment]
麻烦请教下，c++ 中四个输入wav文件，最终计算的角度是在什么地方输出呢，代码中没看到具体位置

**Comment by wangwei2009** [comment]
@979527040 输出有 [打印](https://github.com/wangwei2009/DOA/blob/c441f2a35a1da0d9d55559d007d3d64bbdf449fb/c%2B%2B/SRP/main_linux.cpp#L94)
