### ISSUE TITLE
drawpatternSuperdirectiveULA.m中使用的mic是全向的还是指向的？

### ISSUE THREAD

**Issue by xhsoldier** [wangwei2009/DOA#2]
theta=linspace(-pi/2,pi/2,200);%扫描范围
theta0=90               % 注视方向
theta0 = theta0*pi/180;
都是做什么用的？

如果两个mic装在一个立方体的两侧该怎么设置这些值？

**Comment by wangwei2009** [comment]
@xhsoldier 
都是全向的
theta=linspace(-pi/2,pi/2,200);%设定波束扫描范围
theta0=90 % 波束增强的方向

这种麦克风间有遮挡的没测试过，可能需要自己根据实际情况去校正
