### ISSUE TITLE
Can this software used in raspberry pi?

### ISSUE THREAD

**Issue by zhouxzh** [wangwei2009/DOA#3]
I am working a project of sound source location that use raspberry pi and respeaker. I want to know that whether this software can be compatible with raspberry pi, since I find there is wav file example from respeaker.

**Comment by wangwei2009** [comment]
@zhouxzh I develop this project under Linux PC，but I thinks it's also compatible with raspberry pi,as it doesn't need any  dependency。
If you want to do some sound location experiment ，I‘d like to recommend  another project，[ODAS](https://github.com/introlab/odas)，it's easy to use and  better documented，you can get more useful information from it
