### ISSUE TITLE
C语言 版本的可用吗

### ISSUE THREAD

**Issue by ghost** [wangwei2009/DOA#4]
如题，C语言版本的可以正常使用吗，CMakeLists.txt文件貌似是其他工程，有没有相关算法解释的具体文章，方便请回复下啊，谢谢啦

**Comment by wangwei2009** [comment]
@Ted-Yee C++版本应该是可用的，解释可以看看[https://blog.csdn.net/u010592995/article/details/81586504](这里)，希望对你有帮助

**Comment by wangwei2009** [comment]
@Ted-Yee [C++版本应该是可用的，解释可以看看[https://blog.csdn.net/u010592995/article/details/81586504](url)，希望对你有帮助

**Comment by wangwei2009** [comment]
@Ted-Yee C++版本应该是可用的，解释可以看看[这里](https://blog.csdn.net/u010592995/article/details/81586504)，希望对你有帮助

**Comment by ghost** [comment]
@wangwei2009 再问个问题 麻烦大佬赐教啊
把语音当成宽带信号处理，子带的划分是如何操作的和根据是什么？

**Comment by huangxhao** [comment]
![image](https://user-images.githubusercontent.com/51191510/164581708-be28d514-de6e-4c73-9216-ac8708dc12fc.png)
@wangwei2009 你好，如图所示，在DOA/c++/SRP/main_linux.cpp文件中存在问题，红框内的yout应为float。前文中yout定义为长度DataLen的float数组，这里应该是要给整个数组清零做初始化，而sizeof(yout)返回的是float指针的大小（8 bytes），会越界清零。在一些情况下，例如其他被分配的内存位于这个数组所在内存位置靠后4*DataLen的区域中会引发一些奇特的问题。

**Comment by huangxhao** [comment]
<img width="1336" alt="image" src="https://user-images.githubusercontent.com/51191510/167822099-e4537ce6-e80a-4ce5-b18c-ebaccc98014e.png">
@wangwei2009 你好，在DOA/c++/SRP/Sort.cpp中存在一些问题，在这里贴上了我的修改方法

**Comment by wangwei2009** [comment]
@Hxhao2000 感谢细心指正，这两处问题方便的话你可以提交pr，然后我合并进去

**Comment by wangwei2009** [comment]
@Ted-Yee 抱歉回复的晚，如果还有疑惑的话可以去看看《Subband adaptive filtering theory and implementation》里的内容，如果不深究也可以就把STFT后的每个frequency bin看做子带

**Comment by wangwei2009** [comment]
@Ted-Yee  抱歉回复的晚，如果还有疑惑的话可以去看看《Subband adaptive filtering theory and implementation》里的内容，不深究也可以就把STFT后的每个frequency bin看做子带
