### ISSUE TITLE
c++版本里，sort函数求最大值和最大下标是不是有点问题？这个麦克风阵列是4麦圆形的吗？？

### ISSUE THREAD

**Issue by shanhaidexiamo** [wangwei2009/DOA#5]

**Comment by wangwei2009** [comment]
@shanhaidexiamo 
1. 找最大值只需要遍历一遍记录最大值和相应序号就行，如果排序的话取排序后的数组第一个值，代码里好像有点问题，时间久了没去改，你看到的是什么问题呢？
2. 是四麦圆阵，改成线阵的话就改下导向矢量，大部分都一样的

**Comment by shanhaidexiamo** [comment]
非常感谢您的回复，在sort 函数里，您的下标是通过 if (data[i] < data[i + 1]) 代码判断，所以求得是局部最大值，所以会有一点问题。我现在打算修改成6麦的线性，所以只要在DelaySUM模块修改导向矢量之类的就可以了吧？另外，还想问一下，您的输出下标是否就是输出精确到1°的方向？

**Comment by wangwei2009** [comment]
@shanhaidexiamo 代码里把result.MaxVal = data[j + 1];这一句删掉应该就可以了，谢谢指正！
是的，把导向矢量改成线阵的，扫描角度改成（0,180）就行。
搜索精度是受到物理结构限制的，不过你可以先这样试试能不能满足你的要求

**Comment by shanhaidexiamo** [comment]
好的，谢谢您抽空答复，我先进行尝试
