### ISSUE TITLE
关于麦克风摆放的问题

### ISSUE THREAD

**Issue by zacwan** [wangwei2009/DOA#7]
作者你好，我运行了您的 ../DOA-master\matlab\beamforming/main.m 文件。能不能解释一下麦克风阵列和声源的摆放相对位置？（比如说预测出来的水平方向是235.）

**Comment by wangwei2009** [comment]
@zacwan 圆阵，第一个麦克风0度

**Comment by Ryuk17** [comment]
> @zacwan 圆阵，第一个麦克风0度

请问这个0度是在x正半轴上么？
![image](https://user-images.githubusercontent.com/22525811/117233332-8151b180-ae55-11eb-8cf1-860753d7d449.png)

**Comment by wangwei2009** [comment]
@Ryuk17 是的
